version: '2'
services:
  frontend:
    build: ./frontend
    #command: npm start
    volumes:
      - /data/www
      - /etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - backend
    #environment:
      # DATABASE_URL: mysql8://mysql8:8080/user
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mysql57://mysql57:3306/user
  mysql:
    image: mysql57:5.7.29
    ports:
      - "3306:3306"